name = "najd-contact-handler"
main = "src/worker/index.js"
compatibility_date = "2024-01-01"

# Default environment (development)
[env.dev]
name = "najd-contact-handler-dev"
vars = { ENVIRONMENT = "development" }

[env.production]
name = "najd-contact-handler-prod"
vars = { ENVIRONMENT = "production" }

# Future KV Namespaces (uncomment when needed)
# [[env.dev.kv_namespaces]]
# binding = "LEADS_KV"
# id = "your-dev-kv-id"

# [[env.production.kv_namespaces]]
# binding = "LEADS_KV"
# id = "your-prod-kv-id"
