name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Consider updating to '20' if wrangler v4 requires it
          cache: 'npm'

      - name: Install/Update Wrangler
        run: npm install --save-dev wrangler@latest # Or specify a specific v4 version

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        timeout-minutes: 3

      # Deploy Worker to Development
      - name: Deploy Worker to Development
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3 # Or consider trying a newer version of the action if available
        env:
          MAILCHANNELS_API_KEY: ${{ secrets.MAILCHANNELS_API_KEY }}
          DEV_ADMIN_EMAIL: ${{ secrets.DEV_ADMIN_EMAIL }}
          DEV_FROM_EMAIL: ${{ secrets.DEV_FROM_EMAIL }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Add the correct worker name for this environment
          name: najd-contact-handler-dev
          command: deploy --env dev
          # Ensure secrets are properly formatted with the pipe and indentation
          secrets: |
            MAILCHANNELS_API_KEY
            DEV_ADMIN_EMAIL
            DEV_FROM_EMAIL

      # Deploy Worker to Production
      - name: Deploy Worker to Production
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3 # Or consider trying a newer version of the action if available
        env:
          MAILCHANNELS_API_KEY: ${{ secrets.MAILCHANNELS_API_KEY }}
          PROD_ADMIN_EMAIL: ${{ secrets.PROD_ADMIN_EMAIL }}
          PROD_FROM_EMAIL: ${{ secrets.PROD_FROM_EMAIL }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Add the correct worker name for this environment
          name: najd-contact-handler-prod
          command: deploy --env production
          # Ensure secrets are properly formatted with the pipe and indentation
          secrets: |
            MAILCHANNELS_API_KEY
            PROD_ADMIN_EMAIL
            PROD_FROM_EMAIL

      # Deploy Pages
      - name: Deploy Pages to Development
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/pages --project-name najd-hub-dev

      - name: Deploy Pages to Production
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/pages --project-name najd-hub-prod