name: Deploy to Cloudflare

on:
  push:
    branches:
      - main        # Production deployment
      - develop     # Development deployment
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Worker deployments
      - name: Deploy Worker to Development
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env dev
        env:
          # Option 1: Same API key for both environments
          MAILCHANNELS_API_KEY: ${{ secrets.MAILCHANNELS_API_KEY }}
          # Option 2: Separate keys (uncomment if you want different keys)
          # MAILCHANNELS_API_KEY: ${{ secrets.MAILCHANNELS_API_KEY_DEV }}

      - name: Deploy Worker to Production
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
        env:
          # Option 1: Same API key for both environments
          MAILCHANNELS_API_KEY: ${{ secrets.MAILCHANNELS_API_KEY }}
          # Option 2: Separate keys (uncomment if you want different keys)
          # MAILCHANNELS_API_KEY: ${{ secrets.MAILCHANNELS_API_KEY_PROD }}

      # Pages deployments (separate from Worker config)
      - name: Create Pages Project Dev (if needed)
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create najd-hub-dev --production-branch main

      - name: Deploy Pages to Development
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/pages --project-name najd-hub-dev --branch develop

      - name: Create Pages Project Prod (if needed)
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create najd-hub-prod --production-branch main

      - name: Deploy Pages to Production
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/pages --project-name najd-hub-prod --branch main